# Generated by Django 6.0.6 on 2026-06-05 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouverture', models.DateTimeField(default=django.utils.timezone.now)),
                ('fermeture', models.DateTimeField(blank=True, null=True)),
                ('fond_ouverture', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('fond_fermeture', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'ordering': ['-ouverture'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('motif', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='caisse.sessioncaisse')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
