# Generated by Django 6.0.6 on 2026-06-05 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirmee', 'Confirmée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile', 'Mobile Money'), ('virement', 'Virement'), ('credit', 'Crédit')], default='especes', max_length=20)),
                ('sous_total', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tva_montant', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='clients.client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=0, max_digits=12)),
                ('remise_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente')),
            ],
        ),
    ]
