# Generated by Django 6.0.6 on 2026-06-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.TextField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
