# Generated by Django 6.0.6 on 2026-06-05 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('poste', models.CharField(choices=[('vendeur', 'Vendeur'), ('caissier', 'Caissier'), ('magasinier', 'Magasinier'), ('comptable', 'Comptable'), ('manager', 'Manager'), ('directeur', 'Directeur')], max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('salaire', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('date_embauche', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employes/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Maladie'), ('maternite', 'Maternité'), ('autre', 'Autre')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='demande', max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='employes.employe')),
            ],
        ),
    ]
