# Generated by Django 6.0.6 on 2026-06-05 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('vente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Facture',
                'ordering': ['-date_emission'],
            },
        ),
    ]
